### PR TITLE
Client data endpoints with tests

### PR DESCRIPTION
**Pull request by cryptopragmatic**
New API endpoints in client (with tests):

/addresses/data/{address} (GET - AddressesData)
/addresses/data/{address}/{key} (GET- AddressesDataKey)
/addresses/data/{address} (POST - AddressesDataKeys)

### CODE REVIEW

**Comment by cryptopragmatic** [comment]
@alexeykiselev, is this failing because I squashed all commits into one?

**Comment by alexeykiselev** [comment]
@cryptopragmatic First of all, thank you for your PRs! It's so cool to have PRs from devs outside the team :)
Checks failed because one of them is not prepared for external PRs. We have disabled this check for external PRs for now. 
I've updated your PR with fresh master, it should pass now.

**Review by nickeskov — CHANGES_REQUESTED** [review]

**Comment by nickeskov** [comment]
@cryptopragmatic Hello! Do you need some help with this PR? Feel free to ask any questions.

**Comment by nickeskov** [comment]
@cryptopragmatic Thanks for your contribution! All issues will be fixed in #829.

**Pull request merged**
